apiVersion: apps/v1
kind: Deployment
metadata:
  name: images-service
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: images-service
  template:
    metadata:
      labels:
        app: images-service
    spec:
      containers:
        - name: images-service
          image: acraksworkshopdev.azurecr.io/images-service:latest
          ports:
            - containerPort: 8082
