apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      containers:
        - name: image-service
          image: acraksworkshopdev.azurecr.io/image-service:latest
          ports:
            - containerPort: 8081
