name: Build and Push Multiple Images to ACR

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      run: |
        az acr login -n ${{ secrets.ACR_NAME }}

    - name: Build and Push gateway image
      run: |
        IMAGE=${{ secrets.ACR_NAME }}.azurecr.io/gateway:latest
        docker build -t $IMAGE ./gateway
        docker push $IMAGE

    - name: Build and Push images-services image
      run: |
        IMAGE=${{ secrets.ACR_NAME }}.azurecr.io/images-service:latest
        docker build -t $IMAGE ./images-service
        docker push $IMAGE

    - name: Build and Push users-services image
      run: |
        IMAGE=${{ secrets.ACR_NAME }}.azurecr.io/users-service:latest
        docker build -t $IMAGE ./users-service
        docker push $IMAGE
